### ISSUE TITLE
OverrideAdapter not working

### ISSUE THREAD

**Issue by ericdudley** [statsig-io/js-client-monorepo#2] opened 2024-05-29 18:27 UTC
Hello,

I am trying to use the new library (using version "0.0.1-beta.42"). It seems like the gate overrides are not functioning when using the react bindings.

## Setup

```
  const overrideAdapter = new LocalOverrideAdapter();

gateOverrides?.forEach(({ gate, enabled }) => {
    overrideAdapter.overrideGate(gate, enabled);
  });

  const client = new StatsigClient(
    'sdkKey',
    {
      userID: 'abc',
    },
    {
      overrideAdapter: overrideAdapter,
      environment: { tier },
      disableLogging: true,
      networkConfig: {
        preventAllNetworkTraffic: true,
      },
    }
  );
```

In component later
```

const { value } = useFeatureGate(
   'mygate'
  );

```

## Expected Behavior

If mygate is in the `gateOverrides` and set to true, the value in the component would be true.

## Actual Behavior

mygate always returns false.

## What I've tried

If I manually call `checkGate` on the statsigClient, I get the correct override value. It seems like this is an issue with the react bindings specifically.

If I `useStatsigClient` and call `checkGate` I get false.

**Comment by daniel-statsig** [comment] 2024-05-29 21:35
Hi there @ericdudley, happy to help here. 

I am about to push an example of how to use the LocalOverrideAdapter in React. From my internal testing I am not able to reproduce this issue.

In my example I have the following:
```tsx
import { useMemo } from 'react';

import { LogLevel } from '@statsig/client-core';
import { StatsigClient } from '@statsig/js-client';
import { LocalOverrideAdapter } from '@statsig/js-local-overrides';
import { StatsigProvider, useFeatureGate } from '@statsig/react-bindings';

import { DEMO_CLIENT_KEY } from '../../utils/constants';

/* eslint-disable no-console */

function useClientWithOverrides(): StatsigClient {
  const { client } = useMemo(() => {
    const overrideAdapter = new LocalOverrideAdapter();
    overrideAdapter.overrideGate('gate_a', false);
    overrideAdapter.overrideGate('gate_b', true);

    const client = new StatsigClient(
      DEMO_CLIENT_KEY,
      { userID: 'a-user' },
      {
        logLevel: LogLevel.Debug,
        overrideAdapter,
      },
    );

    client.initializeSync();

    return { client };
  }, []);

  return client;
}

function Content() {
  const gateA = useFeatureGate('gate_a');
  const gateB = useFeatureGate('gate_b');

  return (
    <div style={{ padding: 16 }}>
      <div>
        gate_a: {gateA.value ? 'Passing' : 'Failing'} ({gateA.details.reason})
      </div>
      <div>
        gate_b: {gateB.value ? 'Passing' : 'Failing'} ({gateB.details.reason})
      </div>
    </div>
  );
}

export default function OverrideAdapterExample(): JSX.Element {
  const client = useClientWithOverrides();

  return (
    <StatsigProvider client={client}>
      <Content />
    </StatsigProvider>
  );
}
```

which is rendering as:

![Screenshot 2024-05-29 at 2 35 18 PM](https://github.com/statsig-io/js-client-monorepo/assets/95646168/b83376fc-f5fd-4820-9bcf-6303d15887d9)

**Comment by daniel-statsig** [comment] 2024-05-30 19:23
Excellent. Closing this issue since it has been resolved. Feel file more if you run into other issues

**Closed by daniel-statsig** 2024-05-30 19:23 UTC
Labels: JS Mono
